apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kobo.fullname" . }}-kobocat
  labels:
    app.kubernetes.io/component: kobocat
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.kobocat.autoscaling.enabled }}
  replicas: {{ .Values.kobocat.replicaCount }}
  {{- end }}
  {{- if .Values.kobocat.strategy }}
  strategy: {{- toYaml .Values.kobocat.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: kobocat
      {{- include "kobo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/kobocat/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/kobocat/configmap.yaml") . | sha256sum }}
        tag: "{{ .Values.kobocat.image.tag }}"
      labels:
        app.kubernetes.io/component: kobocat
        {{- include "kobo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kobo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.kobocat.image.repository }}:{{ .Values.kobocat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kobocat.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/
              port: http
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.kobocat.resources | nindent 12 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.postgresql.fullname" .) .Values.postgresql.auth.existingSecret }}
                  key: postgres-password
            - name: DATABASE_URL
              value: {{ (include "kobo.postgresql.kc_url" .) }}
            {{- end }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.mongodb.fullname" .) .Values.mongodb.auth.existingSecret }}
                  key: mongodb-passwords
            - name: MONGO_DB_URL
              value: {{ (include "kobo.mongodb.url" .) }}
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "kobo.redis.fullname" .) .Values.redis.auth.existingSecret }}
                  key: redis-password
            - name: REDIS_SESSION_URL
              value: {{ (include "kobo.redis.url" .) }}/1
            - name: SERVICE_ACCOUNT_BACKEND_URL
              value: {{ (include "kobo.redis.url" .) }}/6
            - name: KOBOCAT_BROKER_URL
              value: {{ (include "kobo.redis.url" .) }}/3
            - name: CACHE_URL
              value: {{ (include "kobo.redis.url" .) }}/5
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "kobo.fullname" . }}-kobocat
            - configMapRef:
                name: {{ include "kobo.fullname" . }}-kobocat
          command: ["/srv/init/run-uwsgi.sh"]
          volumeMounts:
          - name: scripts
            mountPath: /srv/init/
          {{- with .Values.kobocat.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        - name: nginx
          image: {{ .Values.nginx.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 32Mi
          volumeMounts:
          - name: static-volume
            mountPath: /static
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
          ports:
            - containerPort: 80
      initContainers:
        - name: init
          image: "{{ .Values.kobocat.image.repository }}:{{ .Values.kobocat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kobocat.image.pullPolicy }}
          command: ["/srv/init/init.sh"]
          volumeMounts:
          - name: static-volume
            mountPath: /static    
          - name: scripts
            mountPath: /srv/init/
          {{- with .Values.kobocat.extraVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "kobo.fullname" . }}-kobocat
            - configMapRef:
                name: {{ include "kobo.fullname" . }}-kobocat

      {{- with .Values.kobocat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kobocat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kobocat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: kobocat
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: scripts
        configMap:
          name: {{ include "kobo.fullname" . }}-kobocat-scripts
          defaultMode: 0777
          items:
          - key: run-uwsgi.sh
            path: run-uwsgi.sh
          - key: init.sh
            path: init.sh
      - name: nginx-conf
        configMap:
          name: {{ include "kobo.fullname" . }}-nginx-kobocat-conf
      {{- with .Values.kobocat.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
